title: "|| स्तोत्रसुधामंजिरी ||"
description: "A minimalist, bloat-free collection of Shlokas and Stotras in Marathi."
theme: null
baseurl: ""
url: "https://stotrasudhamanjiri.github.io"

collections:
  devatas:
    output: true
  shlokas:
    output: true